name: Deploy to Production

on:
  push:
    branches: [main]

# Add concurrency to ensure only one deployment runs at a time
concurrency:
  group: production-deploy-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build-and-deploy:
    name: Build and Deploy
    runs-on: ubuntu-latest
    environment: Prod
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          ref: main # Ensure we're getting the latest code from main

      - name: Get Bun version from .tool-versions
        id: get-bun-version
        run: echo "BUN_VERSION=$(grep 'bun' .tool-versions | awk '{print $2}')" >> $GITHUB_OUTPUT

      - name: Get Node.js version from .tool-versions
        id: get-node-version
        run: echo "NODE_VERSION=$(grep 'nodejs' .tool-versions | awk '{print $2}')" >> $GITHUB_OUTPUT

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ steps.get-node-version.outputs.NODE_VERSION }}

      - name: Setup Bun
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: ${{ steps.get-bun-version.outputs.BUN_VERSION }}

      - name: Cache dependencies
        uses: actions/cache@v4
        with:
          path: ~/.bun/install/cache
          key: ${{ runner.os }}-bun-${{ hashFiles('**/bun.lockb') }}
          restore-keys: ${{ runner.os }}-bun-

      - name: Cache build
        uses: actions/cache@v4
        with:
          path: |
            dist
            .rspack-cache
          key: ${{ runner.os }}-build-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-build-

      - name: Install dependencies
        run: bun install --frozen-lockfile

      - name: Build
        run: bun run build
        
      - name: Copy public assets to dist
        run: |
          echo "Copying public folder content to dist directory"
          cp -r public/* dist/
          echo "Listing dist directory content after copy:"
          ls -la dist/

      - name: Deploy via FTP
        uses: SamKirkland/FTP-Deploy-Action@v4.3.4
        with:
          server: ${{ secrets.FTP_SERVER }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          port: ${{ secrets.FTP_PORT }}
          protocol: ftp
          local-dir: ./dist/
          server-dir: /public_html/
          dangerous-clean-slate: true
          timeout: 120000
          log-level: verbose 